# Generated by Django 4.1.6 on 2023-03-02 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('TELUGU', 'TELUGU'), ('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH'), ('TAMIL', 'TAMIL'), ('KANNADA', 'KANNADA')], max_length=24)),
                ('type', models.CharField(choices=[('CHILDREN', 'CHILDREN'), ('ADULT', 'ADULT'), ('FAMILY', 'FAMILY'), ('NONE', 'NONE')], default='NONE', max_length=24, null=True)),
                ('movie_release_date', models.DateTimeField()),
                ('movie_duration', models.PositiveIntegerField(default=180, help_text='Lenght of movie in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('numberofscreens', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.city')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capaticy', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('price', models.IntegerField(default=150)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.theater')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timings')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('booking_status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('AVAILABLE', 'AVAILABLE'), ('NOT_AVAILABLE', 'NOT_AVAILABLE')], default='AVAILABLE', max_length=24)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.show')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('seat_number', models.PositiveIntegerField()),
                ('user', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.theater')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.timings')),
            ],
        ),
    ]
