# Generated by Django 4.1.6 on 2023-03-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('CHILDREN', 'CHILDREN'), ('ADULT', 'ADULT'), ('FAMILY', 'FAMILY'), ('NONE', 'NONE'), ('THRILLER', 'THRILLER'), ('COMEDY', 'COMEDY')], default='NONE', max_length=24, null=True),
        ),
    ]
