# Generated by Django 4.1.6 on 2023-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
